name: Build PyPI package

on:
  workflow_dispatch:
  workflow_call:
  release:
    types: [ published ]

jobs:
  build-publish-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.8" ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          pipx install poetry==1.4.2
        shell: bash

      - name: Poetry path
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        shell: bash

      - name: Build FAST-PEDAGO
        run: poetry build
        shell: bash

      - name: publish FAST-PEDAGO to PyPI
        env:
          TOKEN: ${{ secrets.PYPI }} # do not use the secret directly in run command, it would write it plainly in the log
        run: |
          poetry config pypi-token.pypi "$TOKEN"
          poetry publish